### ISSUE TITLE
Add face cards and card Art

### ISSUE THREAD

**Issue by Htjackson8506** [LeitMoth/blackjack-the-digital-realm#9]
Art for the cards (Suit and number)

**Comment by cfp04** [comment]
Note that adding art will require more than just modifying the `PlayingCard` widget.

In firestore, we don't store cards names, we only store integers. So you will need to convert between integers and cards at some point.

You will need to modify this method specifically, (and don't forget to handle aces):
https://github.com/LeitMoth/blackjack-the-digital-realm/blob/e1797e6bec6216b882013a5bf1fd243e97495072/lib/game_state.dart#L28-L30

After that, you can just modify `PlayingCard` to make it pretty.

**Comment by jonesamelia** [comment]
I would like to claim this issue.

**Comment by cfp04** [comment]
Great! Please don't fork the repo yet, I need to fix #13 first, or you will run into weird errors. It is a firebase related thing so I need to fix it myself. I should be able to get in done in the next 30 minutes though.

**Comment by cfp04** [comment]
Alright, #13 is fixed on the most recent commit.
You should be good to start working, I have assigned this issue to you.

**Comment by jonesamelia** [comment]
Great! Thank you!
